config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    collection { post :import}
  end

  resources :courses do
      member do
          get 'home'
      end
  end
  
  get 'test_social' => 'social#index'
  get 'test_social/:id/test' => 'social#test' 
  get 'test_social/:id' => 'social#test_course' 
  post 'test_social/:id/test' => 'social#create'


  get 'test_eneagrama' => 'psychological#index'
  get 'test_eneagrama/test' => 'psychological#test' 
  post 'test_eneagrama/test' => 'psychological#create' 

  get 'usuarios' => 'users#index'
  get 'cursos/test' => 'courses#index' 
  get 'curso/:id' => 'courses#show' 
  get 'my_courses' => 'courses#my_courses_list'

  get 'grupos' => 'groups#index'
  post  'grupos' => 'groups#index' 
  get 'mi_equipo' => 'groups#my_group'

  get 'excel' => 'groups#groups_list'

  get 'complaint' => 'groups#get_complaint'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared/_footer.html.erb
<div class="container">
    <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">TeamMaker</h5>
            <ul>
                <li><a class="grey-text text-lighten-2 s8" >TeamMaker es una herramienta creada por estudiantes de la Universidad de Santiago para formar equipos de trabajo en cursos.</a></li>
            </ul>

        </div>
        <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Enlaces</h5>
            <ul>
                <li><a class="grey-text text-lighten-2" href="http://www.informatica.usach.cl/">DIINF Usach</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/shared/_navbar.html.erb
 <div class="navbar-fixed">
 <nav>
  <div class="nav-wrapper">
    <%= link_to "TeamMaker", root_path, class: "brand-logo Motion", style: "padding-left:15px;font-size:30pt !important; "%>
      <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>  
          <ul id="dropdown_user" class="dropdown-content" style="margin-top: 64px;">
            <!-- <li><%= link_to 'Cuenta',edit_user_registration_path %></li>-->
            <li role="separator" class="divider"></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%></li>
          </ul>
          <ul id="dropdown_course" class="dropdown-content" style="margin-top: 64px;">
            <% current_user.courses.each do |course| %>
              <li><%= link_to course.code,course_path(course) %></li>
            <% end %>
          </ul>
          <ul id="dropdown_group" class="dropdown-content" style="margin-top: 64px;">
            <% current_user.courses.each do |course| %>
              <li><%= link_to course.code, grupos_path %></li>
            <% end %>
          </ul>
          <ul id="dropdown_test" class="dropdown-content" style="margin-top: 64px;">
            <% if current_user.accept_model? %>
              <li>
                <% if current_user.test_count != 6 %>
                  <%= link_to 'Personalidad<span class="new badge red" data-badge-caption="test">1</span>'.html_safe,test_eneagrama_path %>
                <% else %>
                  <%= link_to 'Personalidad<span class="new badge green" data-badge-caption="resuelto"></span>'.html_safe,test_eneagrama_path %>
                <% end %>
              </li>
              <li>
                <% if current_user.tests.find_by(kind: 2, answered: false) %>
                  <%= link_to 'Social <span class="new badge red" style="margin-left:63px" data-badge-caption="test">2+</span>'.html_safe,test_social_path %>
                <% elsif current_user.tests.find_by(kind: 3, answered: false) %>
                  <%= link_to 'Social<span class="new badge red" style="margin-left:53px" data-badge-caption="test">1</span>'.html_safe,test_social_path %>
                <% else %>
                  <%= link_to 'Social<span class="new badge green" data-badge-caption="resuelto" style="margin-left:63px"></span>'.html_safe,test_social_path %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <% if current_user.rol == 3 && current_user.accept_model == true %>
          <% if current_user.accept_model? %>
            <li class="<%= 'active' if current_page?(mi_equipo_path) %>"><%= link_to "Mis grupos", mi_equipo_path %></li>
           <li class="<%= 'active' if current_page?(courses_path) %>"><%= link_to "Mis cursos", my_courses_path %></li>
           <% end %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown_test">
              Mis test
              <% if current_user.accept_model? %>
                <% if current_user.tests.find_by(kind: 1, answered: false).present? ||
                      current_user.tests.find_by(kind: 2, answered: false).present? || 
                      current_user.tests.find_by(kind: 3, answered: false).present? 
                %>
                  <span class="new badge" data-badge-caption="">Test pendientes</span>
                <% else %>
                  <span class="new badge" data-badge-caption="">Test resueltos</span>
                <% end %> 
   
              <% end %>
                <i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
          <% if current_user.rol == 0 %>
            <li class="<%= 'active' if current_page?(grupos_path) %>"><%= link_to "Grupos", grupos_path%></li>
            <li class="<%= 'active' if current_page?(usuarios_path) %>"><%= link_to "Usuarios", usuarios_path%></li>
            <li class="<%= 'active' if current_page?(courses_path) %>"><%= link_to "Cursos", courses_path%></li>
          <% elsif current_user.rol == 1 || current_user.rol == 2 %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown_course">Mis cursos<i class="material-icons right">arrow_drop_down</i></a></li>
            <li class="<%= 'active' if current_page?(grupos_path) %>"><%= link_to "Mis grupos", grupos_path %></li>
          <% end %>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown_user"><%=current_user.email%><i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <%= link_to "Iniciar sesión", new_user_session_path, :class => "btn btn-default navbar-btn waves-effect waves-light features-black"%>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<ul class="side-nav" id="mobile">
        <% if user_signed_in? %>
          <ul id="dropdown_user_mobile" class="dropdown-content" style="margin-top: 48px;">
            <li><%= link_to 'Cuenta',edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%></li>
          </ul>
          <ul id="dropdown_course_mobile" class="dropdown-content" style="margin-top: 64px;">
            <% current_user.courses.each do |course| %>
              <li><%= link_to course.code,course_path(course) %></li>
            <% end %>
          </ul>
          <ul id="dropdown_test_mobile" class="dropdown-content" style="margin-top: 48px;">
            <% if current_user.accept_model? %>
              <li>
                <% if current_user.test_count != 6 %>
                  <%= link_to 'Personalidad<span class="new badge red" style="margin-left:26.5px" data-badge-caption="test">1</span>'.html_safe,test_eneagrama_path %>
                <% else %>
                  <%= link_to 'Personalidad<span class="new badge green" style="margin-left:26.5px" data-badge-caption="resuelto"></span>'.html_safe,test_eneagrama_path %>
                <% end %> 
              </li>
              <li>
                <% if current_user.tests.find_by(kind: 2, answered: false).present? %>
                  <%= link_to 'Afinidad social<span class="new badge red mid" data-badge-caption="test">2+</span>'.html_safe,test_social_path %>
                <% elsif current_user.tests.find_by(kind: 3, answered: false).present? %>
                  <%= link_to 'Afinidad social<span class="new badge red mid" data-badge-caption="test">1</span>'.html_safe,test_social_path %>
                <% else %>
                  <%= link_to 'Afinidad social<span class="new badge green mid" data-badge-caption="resuelto"></span>'.html_safe,test_social_path %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <% if current_user.rol == 3 && current_user.accept_model == true %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown_test_mobile">
              Mis test
              <% if current_user.accept_model? %>
                <% if current_user.tests.find_by(kind: 1, answered: false).present? ||
                      current_user.tests.find_by(kind: 2, answered: false).present? ||
                      current_user.tests.find_by(kind: 3, answered: false).present?
                %>
                  <span class="new badge" data-badge-caption="">Test pendientes</span>
                <% else %>
                  <span class="new badge" data-badge-caption="">Test resueltos</span>
                <% end %> 
   
              <% end %>
                <i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
          <% if current_user.rol == 0 %>
            <li class="<%= 'active' if current_page?(grupos_path) %>"><%= link_to "Grupos", grupos_path%></li>
            <li class="<%= 'active' if current_page?(usuarios_path) %>"><%= link_to "Usuarios", usuarios_path%></li>
            <li class="<%= 'active' if current_page?(courses_path) %>"><%= link_to "Cursos", courses_path%></li>
          <% elsif current_user.rol == 1 || current_user.rol == 2 %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown_course_mobile">Mis cursos<i class="material-icons right">arrow_drop_down</i></a></li>
          <li class="<%= 'active' if current_page?(grupos_path) %>"><%= link_to "Mis grupos", grupos_path%></li>  
          <% end %>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown_user_mobile"><%=current_user.email%><i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <%= link_to "Iniciar sesión", new_user_session_path, :class => "waves-effect waves-light btn features-black"%>
        <% end %>
      </ul>