config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    collection { post :import}
  end

  resources :courses do
      member do
          get 'home'
      end
  end
  
  get 'test_social' => 'social#index'
  get 'test_social/:id/test' => 'social#test' 
  get 'test_social/:id' => 'social#test_course' 
  post 'test_social/:id/test' => 'social#create'


  get 'test_eneagrama' => 'psychological#index'
  get 'test_eneagrama/test' => 'psychological#test' 
  post 'test_eneagrama/test' => 'psychological#create' 

  get 'usuarios' => 'users#index'
  get 'cursos/test' => 'courses#index' 
  get 'curso/:id' => 'courses#show' 
  get 'my_courses' => 'courses#my_courses_list'

  get 'grupos' => 'groups#index'
  post  'grupos' => 'groups#index' 
  get 'mi_equipo' => 'groups#my_group'

  get 'excel' => 'groups#groups_list'

  get 'complaint' => 'groups#get_complaint'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    def get_complaint
        require 'matrix'
        course = Course.find(params[:course])
        allStudents = course.users.where(rol: 3)
        students = []
        studentsIndexes = Hash.new
        studentActualIndex = 0
        allStudents.each do |student|
            if student.group.present?
                students << student
                studentsIndexes[student.id] = studentActualIndex
                studentActualIndex += 1
            end
        end
        indexUser = 0
        @Mp = Matrix.build(9, students.size){ 0 }
        students.each_with_index do |p, index|
            if p.eneatype.present?
                @Mp.send(:[]=, p.eneatype.number-1, index, 1)
            else
                @Mp.send(:[]=, rand(0..8), index, 1)
            end
        end
        @Mscod = Matrix.build(students.size, students.size){ '!!!!' }
        students.each_with_index do |p, index|
          positivo = p.tests.find_by(kind: 2).answers
          negativo = p.tests.find_by(kind: 3).answers
          
          positivo.each do |creeAceptacion|
            if creeAceptacion.answer == 0 # si cree
                students.each_with_index do |person, indexa|
                if person.id == creeAceptacion.number
                  indexUser = indexa
                end
              end
              if @Mscod[index, indexUser][@Mscod[index, indexUser].length-4] == '!'
                @Mscod.send(:[]=, index, indexUser, '(' + @Mscod[index, indexUser][1..3])
                @Mscod.send(:[]=, indexUser, index, '(' + @Mscod[index, indexUser][1..3])
              elsif @Mscod[index, indexUser][@Mscod[index, indexUser].length-1] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0..2] + ')')
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0..2] + ')')
              end
            end
          end
        
          negativo.each do |creeRechazo|
            if creeRechazo.answer == 0 # no cree
                students.each_with_index do |person, index|
                if person.id == creeRechazo.number
                  indexUser = index
                end
              end
              if @Mscod[index, indexUser][@Mscod[index, indexUser].length-4] == '!'
                @Mscod.send(:[]=, index, indexUser, '[' + @Mscod[index, indexUser][1..3])
                @Mscod.send(:[]=, indexUser, index, '[' + @Mscod[index, indexUser][1..3])
              elsif @Mscod[index, indexUser][@Mscod[index, indexUser].length-1] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0..2] + ']')
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0..2] + ']')
              end
            end
          end

          positivo.each do |creeAceptacion|
            if creeAceptacion.answer == 1 # si ELIGE
                students.each_with_index do |person, indexa|
                if person.id == creeAceptacion.number
                  indexUser = indexa
                end
              end
              if @Mscod[index, indexUser][@Mscod[index, indexUser].length-3] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0] + 'E' + @Mscod[index, indexUser][2..3])
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0] + 'E' + @Mscod[index, indexUser][2..3])
              elsif @Mscod[index, indexUser][@Mscod[index, indexUser].length-2] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0..1] + 'e' + @Mscod[index, indexUser][3])
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0..1] + 'e' + @Mscod[index, indexUser][3])
              end
            end
          end

          negativo.each do |creeRechazo|
            if creeRechazo.answer == 1 # no ELIGE
                students.each_with_index do |person, index|
                if person.id == creeRechazo.number
                  indexUser = index
                end
              end
              if @Mscod[index, indexUser][@Mscod[index, indexUser].length-3] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0] + 'R' + @Mscod[index, indexUser][2..3])
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0] + 'R' + @Mscod[index, indexUser][2..3])
              elsif @Mscod[index, indexUser][@Mscod[index, indexUser].length-2] == '!'
                @Mscod.send(:[]=, index, indexUser, @Mscod[index, indexUser][0..1] + 'r' + @Mscod[index, indexUser][3])
                @Mscod.send(:[]=, indexUser, index, @Mscod[index, indexUser][0..1] + 'r' + @Mscod[index, indexUser][3])
              end
            end
          end
        end

         # Matriz de relaciones interpersonales (Mr)
         @Mr = Matrix[]
         @Mr = Matrix.rows(@Mr.to_a << [0,1,0,1,1,1,1,0,0])
         @Mr = Matrix.rows(@Mr.to_a << [1,1,1,1,1,0,1,1,0])
         @Mr = Matrix.rows(@Mr.to_a << [0,1,1,0,1,0,1,0,1])
         @Mr = Matrix.rows(@Mr.to_a << [1,1,0,1,0,0,0,1,0])
         @Mr = Matrix.rows(@Mr.to_a << [1,1,1,0,1,1,1,0,0])
         @Mr = Matrix.rows(@Mr.to_a << [1,0,0,0,1,0,1,0,1])
         @Mr = Matrix.rows(@Mr.to_a << [1,1,1,0,1,1,1,1,0])
         @Mr = Matrix.rows(@Mr.to_a << [0,1,0,1,0,0,1,0,1])
         @Mr = Matrix.rows(@Mr.to_a << [0,0,1,0,0,1,0,1,1])
 
         # Matriz eneagramatica Me = Mp^t(Mr*Mp)
         @Me = Matrix[]
         @Me = @Mp.transpose * (@Mr * @Mp)
 
         # Compatibilidad eneagramatica con uno mismo = 1
         for i in 1..@Me.row_size
           @Me.row(i-1).each_with_index do |e, index|
             if i-1 == index
               @Me.send(:[]=, i-1, index, 1)
             end
           end
         end
 
         # Matriz social decodificada
         @Ms = @Mscod.clone
         socioValor = 0.0
         for i in 1..@Ms.row_size
           @Ms.row(i-1).each_with_index do |e, index|
             if e[0] == '('
               socioValor = socioValor + 0.2
             elsif e[0] == '['
               socioValor = socioValor - 0.2
             end
             if e[1] == 'E'
               socioValor = socioValor + 0.3
             elsif e[1] == 'R'
               socioValor = socioValor - 0.3
             end
             if e[2] == 'e'
               socioValor = socioValor + 0.3
             elsif e[2] == 'r'
               socioValor = socioValor - 0.3
             end
             if e[3] == ')'
               socioValor = socioValor + 0.2
             elsif e[3] == ']'
             elsif i-1 == index
               socioValor = 1
             end
 
             # Normalización
             socioValor = (socioValor + 1)/2
 
 
             @Ms.send(:[]=, i-1, index, socioValor.round(3))
             socioValor = 0.0
           end
         end
 
         @mp = Matrix.zero(students.size, 1)
         @mg = Matrix.zero(students.size, 1)
         @ma = Matrix.zero(students.size, 1)
 
         students.each_with_index do |p, i|
            # @mp.send(:[]=, i, 0, p.programs.first.id.to_f)
            @mp.send(:[]=, i, 0, rand(1..4))
             @mg.send(:[]=, i, 0, p.sex.to_f)
             @ma.send(:[]=, i, 0, p.age.to_f)
         end
 
         @mpn = normalizar(@mp.clone)
         @man = normalizar(@ma.clone)
         # Matriz social codificada 
         @Mes = Matrix[]
         @Mes = @Me + @Ms
         @totalEstudiantes = @Mes.row_size
         # Correccion de decimales
         for i in 1..@Mes.row_size
           @Mes.row(i-1).each_with_index do |e, index|
             @Mes.send(:[]=, i-1, index, e.round(2))
           end
         end
         
         @Map_pre =  normalizar(@Mes.clone )            # Matriz de aptitud
         
         @Map = Matrix.hstack(@Map_pre, @mpn, @man, @mg)

         pt = promedio_atributos(@Map)

         #p = generar_Individuos(5, @Map.row_size/5, 5, @Map.row_size,@Map.row_size).clone

         #pi             = promedio_por_individuo(p,5,@Map.row_size/5,pt.count,5).clone

         groups = get_groups course

         ptGroups = []
         logger.debug groups
         logger.debug studentsIndexes

         acums = Hash.new
         groups.each do |group_number, members|
            logger.debug group_number
            logger.debug members
            if group_number.present?
                groupData = []
                members.each do|member|
                    groupData << @Map.row(studentsIndexes[member.user_id])
                end

                groupDataMatrix = Matrix.rows(groupData)

                ptGroup = promedio_atributos(groupDataMatrix)
                ptGroups << ptGroup
                acum  = 0.0
                for i in 0..pt.count-1
                    acum  = acum + (pt[i]-ptGroup[i])**2
                end
                acums[group_number] = (acum/@Map.row_size).round(3)
            end
         end

         @courseName = course.code

         @data = acums
 
        respond_to do |format|
           format.xlsx
        end

        #debugData = {:students => students, :indexes => studentsIndexes, :map => @Map, :pt => pt, :g => groups, :data => @data}
        #render plain: debugData 
    end
  
  def index
    # 1.CONVERSION DE DATOS DEL MODELO PSICOSOCIAL
    require 'matrix'
    if current_user.rol == 0
      @courses_show = Course.all
    else 
      @courses_show = current_user.courses
    end
    if params[:curso] 
      @courses_show = [Course.find(params[:curso])]
    end
    @grupos = []
    @course_title = []
    @status_curso = ''
    if params[:porGrupo] &&  params[:porGrupo].to_i != 0
      @courses_show.each_with_index do |curso, indice|
        #curso = Course.first 
        estudiantes = curso.users.where(rol: 3)

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<div class="" style="padding-top:5%">
    <div class="container">
        <div class="row">
            <div class="col l12 s12 center-align">
                <h3 style="display: inline"><b>Grupos de trabajo</b></h3>
                <hr style="height: 5px;background-color: #2196F3;border-color: transparent !important;margin-bottom:20px">
                <% if @status && @status == 'NO ES POSIBLE GENERAR LOS EQUIPOS DE:' %>
                <div class="card-panel card-fix red lighten-4 red-text center-align">
                    <i class="material-icons medium">mood_bad</i>
                    <h5 class="h5-fix"><b>¡Ups! Algo no salió bien ... </b></h5>
                    <p style="margin: 4px;"> <%= @status %> </p>
                    <p style="margin: 4px;"><b> <%= @status_curso %> / </b></p>
                    <p>Esto puede deberse a que el curso no cuenta con la cantidad apropiada de estudiantes para generar los equipos, porque ingresó una cantidad de estudiantes por grupo menor a <b>3</b> o porque los alumnos del curso no han contestado sus test.</p>
                </div>
                <% elsif @status && @status == '¡GRUPOS GENERADOS CON ÉXITO!' %>
                <div class="card-panel card-fix green lighten-4 green-text center-align">
                    <i class="material-icons medium ">mood</i>
                    <h5 class="h5-fix"><b>Todo salió bien ... </b></h5>
                    <p class="alert" style="margin: 4px;"> <%= @status %> </p>
                </div>
                <% end %>
            </div>

            <div class="col l3 m6 s8 offset-m3 offset-s2" align="center">
                <div class="card-panel">
                    <p><b>GENERAR GRUPOS</b></p>
                    <%= form_tag({:action => "index"}) do %>
                    <div class="input-field fix-placeholder">
                        <input placeholder="N° de estudiantes" id="porGrupo" name="porGrupo" type="number" class="validate">
                    </div>
                    <div class="input-field fix-placeholder">
                        <select placeholder="Curso" id="curso" name="curso" type="number" class="validate">
                            <% if current_user.rol == 1 || current_user.rol == 2 %>
                                <% current_user.courses.each do |course| %>
                                <option value="<%= course.id %>"><%= course.code %></option>
                                <% end %>
                            <% elsif current_user.rol == 0 %>
                                <% Course.all.each do |course| %>
                                <option value="<%= course.id %>"><%= course.code %></option>
                                <% end %>
                            <% end %>
                        </select>
                    </div>
                    <%= submit_tag "CREAR", class: 'btn blue waves-light' %>
                    <% end %>
                </div>
            </div>

            <div class="col l9 m12 s12">
                <div class="card-panel blue-grey darken-2 white-text" align="left" style="padding-bottom: 6px;">
                    <h5 align="center"><b>INFORMACIÓN</b></h5>
                    <p>Al conformar los equipos de trabajo considere lo siguiente:</p>
                    <li>N° de estudiantes mínimo por grupo deben ser 3 estudiantes.</li>
                    <li>Considere que la cantidad de integrantes por grupo no se diferencie por más de un estudiante.</li>
                    <li>Verifique que todos los alumnos del curso hayan respondido los test correspondientes, quien no lo haya hecho no será incluido en ningún equípo.</li>
                    <p></p>
                </div>
            </div>

            <% if current_user.rol == 1 || current_user.rol == 2 %>
                <% @courses_show.each do |course| %>
                <div class="col s12 center-align">
                    <div class="card blue black-text">
                        <div class="card-content">
                            <h4> Curso: <%= course.code %></h4>
                            <%= link_to "EXPORTAR", excel_path(format: :xlsx, course: course.id), class: 'btn white waves-light black-text' %>
                            <!-- <%= link_to "COMPLAINT", complaint_path(format: :xlsx, course: course.id), class: 'btn blue waves-light' %> -->
                        </div>
                        <% if course.groups.exists? %>
                        <div class="card-tabs black-text">
                            <ul class="tabs tabs-fixed-width tabs-transparent black-text">
                                <% @course_groups[course.id].each do |group_number, members| %>
                                    <li class="tab black-text"><a href="#group<%= group_number.to_s + course.id.to_s %>">grupo <%= group_number %></a></li>
                                <% end %>
                            </ul>
                        </div>
                        <div class="card-content" style="background-color:#1e87da">
                            <div class=" row">
                                <% @course_groups[course.id].each do |group_number, members| %>
                                     <% if group_number.present? %>
                                        <div id="group<%= group_number.to_s + course.id.to_s %>">
                                            <%  members.each do |rel| %>
                                                <% if rel.user.present?  %>
                                                    <!-- Modal Ver estudiante -->
                                                    <div id="verEstudiante<%= rel.user.id%>" class="modal">
                                                        <%= render :partial => "users/shared/show_user", locals: {user: rel.user} %>
                                                    </div> 
                                                    <div class="col l6 m12 s12">
                                                        <div class="card horizontal white darken-2 lighten-1 black-text z-depth-5">
                                                            <div class=" orange darken-5 card-image" style="width: 20% !important;color:#ffe0b2">
                                                                <p align="center" style="padding-top:10px">ENEATIPO</p>
                                                                <% if rel.user.eneatype != nil %>
                                                                    <h1><%= rel.user.eneatype.number %></h1>
                                                                <% else %>
                                                                    <p>Número</p>
                                                                <% end %>
                                                            </div>
                                                            <div class="card-stacked">
                                                                <div class="card-content">
                                                                    <h5 class="flow-text" align="center"><b><%= rel.user.name + ' ' + rel.user.surname %></b></h5>
                                                                    <p class="flow-text" align="center">Carrera: <%= rel.user.programs.first.name %></p>
                                                                    <p class="flow-text" align="center">Sexo: <%= rel.user.sex == 0 ? "Femenino" : "Masculino" %></p>
                                                                </div>
                                                                <div class="card-action">
                                                                    <a class="orange-text modal-trigger" href="#verEstudiante<%= rel.user.id%>">Ver más...</a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                        <% else %>
                        <div class="card-content" style="background-color:#1e87da">
                            <h5>No hay grupos formados en este curso</h5>
                        </div>
                        <% end %>
                    </div>
                </div>
                <% end %>

            <% elsif current_user.rol == 0 %>
                <% @courses_show.each do |course| %>
                <div class="col s12 center-align">
                    <div class="card blue black-text">
                        <div class="card-content">
                            <h4> Curso: <%= course.code %></h4>
                            <%= link_to "EXPORTAR", excel_path(format: :xlsx, course: course.id), class: 'btn white waves-light black-text' %>
                            <!-- <%= link_to "COMPLAINT", complaint_path(format: :xlsx, course: course.id), class: 'btn blue waves-light' %> -->
                        </div>
                        <% if course.groups.exists? %>
                        <div class="card-tabs black-text">
                            <ul class="tabs tabs-fixed-width tabs-transparent black-text">
                                <% @course_groups[course.id].each do |group_number, members| %>
                                    <li class="tab black-text"><a href="#group<%= group_number.to_s + course.id.to_s %>">grupo <%= group_number %></a></li>
                                <% end %>
                            </ul>
                        </div>
                        <div class="card-content" style="background-color:#1e87da">
                            <div class=" row">
                                <% @course_groups[course.id].each do |group_number, members| %>
                                     <% if group_number.present? %>
                                        <div id="group<%= group_number.to_s + course.id.to_s %>">
                                            <%  members.each do |rel| %>
                                                <% if rel.user.present?  %>
                                                    <!-- Modal Ver estudiante -->
                                                    <div id="verEstudiante<%= rel.user.id%>" class="modal">
                                                        <%= render :partial => "users/shared/show_user", locals: {user: rel.user} %>
                                                    </div> 
                                                    <div class="col l6 m12 s12">
                                                        <div class="card horizontal white darken-2 lighten-1 black-text z-depth-5">
                                                            <div class=" orange darken-5 card-image" style="width: 20% !important;color:#ffe0b2">
                                                                <p align="center" style="padding-top:10px">ENEATIPO</p>
                                                                <% if rel.user.eneatype != nil %>
                                                                    <h1><%= rel.user.eneatype.number %></h1>
                                                                <% else %>
                                                                    <p>Número</p>
                                                                <% end %>
                                                            </div>
                                                            <div class="card-stacked">
                                                                <div class="card-content">
                                                                    <h5 class="flow-text" align="center"><b><%= rel.user.name + ' ' + rel.user.surname %></b></h5>
                                                                    <p class="flow-text" align="center">Carrera: <%= rel.user.programs.first.name %></p>
                                                                    <p class="flow-text" align="center">Sexo: <%= rel.user.sex == 0 ? "Femenino" : "Masculino" %></p>
                                                                </div>
                                                                <div class="card-action">
                                                                    <a class="orange-text modal-trigger" href="#verEstudiante<%= rel.user.id%>">Ver más...</a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                        <% else %>
                        <div class="card-content" style="background-color:#1e87da">
                            <h5>No hay grupos formados en este curso</h5>
                        </div>
                        <% end %>
                    </div>
                </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/groups/my_group.html.erb
<div style="padding-top:3%">
    <div class="container">
        <div>
            <% if @my_groups != nil %>
                <% @my_groups.each do |group| %>
                    <div class="row center-align">
                    <h2 style="display: inline"><b>
                    Curso: <%= group[0].course.code %> / Grupo n°<%= group[0].group_number %> 
                    </b></h2>
                    <hr style="background-color:#2196F3;height: 5px;border-color: transparent !important;">
                    <div style="padding-top: 50px">
                    <% group.each do |user_course| %>
                        <% estudiante = user_course.user %>
                        <div class="col l6 m8 s12">
                            <div class="card horizontal <% if current_user.email == estudiante.email %> orange <% else %> blue <% end %> darken-2 lighten-1 white-text z-depth-5">
                                <div class=" <% if current_user.email == estudiante.email %> orange <% else %> blue <% end %> darken-5 card-image" style="width: 20% !important;color:<% if current_user.email == estudiante.email %> #ffe0b2 <% else %> #bbdefb <% end %>">
                                    <p align="center">ENEATIPO</p>
                                    <% if estudiante.eneatype != nil %>
                                    <h1><%= estudiante.eneatype.number %></h1>
                                    <% else %>
                                    <p>Número</p>
                                    <% end %>
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <h5 class="flow-text" align="center"><b><%= estudiante.email %></b></h5>
                                        <hr class="<% if current_user.email == estudiante.email %> orange <% else %> blue <% end %> lighten-4" style="height: 1px;border-color: transparent !important;">
                                        <p align="justify">
                                            <% if estudiante.eneatype != nil %>
                                            <% if estudiante.eneatype.number == 1 %>
                                            SELECCIONADORES: Estas personas creen tener una misión en la vida, lo que las lleva a desear mejorar el mundo de diversas formas...
                                            <% elsif estudiante.eneatype.number == 2 %>
                                            COMPARTIDORES: Ser generosos y desvivirse por los demás les hace pensar que su forma de ser es la más preciosa y la que tiene...
                                            <% elsif estudiante.eneatype.number == 3 %>
                                            EFICIENTES: Son las «estrellas» de la naturaleza humana, y la gente suele admirarlos por su estilo y sus logros personales...
                                            <% elsif estudiante.eneatype.number == 4 %>
                                            PROFUNDOS: Creen ser distintos a los demás seres humanos y que, por lo tanto, nadie puede comprenderlos ni amarlos lo suficiente...
                                            <% elsif estudiante.eneatype.number == 5 %>
                                            CONOCEDORES: Más que cualquiera de los demás tipos, desean descubrir por qué las cosas son como son...
                                            <% elsif estudiante.eneatype.number == 6 %>
                                            RESPONSABLES: Son los más leales a sus amigos y fieles a sus creencias. Se hundirán con el barco y perseverarán en las relaciones...
                                            <% elsif estudiante.eneatype.number == 7 %>
                                            DIVERTIDOS: Asisten a la vida con curiosidad, optimismo y espíritu de aventura, como niños en una tienda de caramelos...
                                            <% elsif estudiante.eneatype.number == 8 %>
                                            FUERTES: Tienen carisma, además de las capacidades físicas y psíquicas para convencer a la gente de que los siga en todo...
                                            <% elsif estudiante.eneatype.number == 9 %>
                                            ARMÓNICOS: Suelen ser personas espirituales que anhelan la conexión con el cosmos y con los demás...
                                            <% end %>
                                            <% else %>
                                        <p>Número</p>
                                        <% end %>
                                        </p>
                                    </div>
                                    <div class="card-action">
                                        <a style="color:<% if current_user.email == estudiante.email %> #ffe0b2 <% else %> #bbdefb <% end %>" href="https://eneagrama.personarte.com/tests-de-personalidad/test-del-jardin-parte-final/" target="_blank">Saber más...</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>    
                <% end %>
            <% else %>
            <div class="row center-align">
            <h2 style="display: inline"><b>Equipo de trabajo</b></h2>
            <hr style="background-color:#2196F3;height: 5px;border-color: transparent !important;">
            </div>
            <h3 align="center" class="thin" style="color:#777373;">Aún no hay equipos formados</h3>
            <h5 align="center" class="thin" style="color:#777373;">Espere a que alguno de sus profesores genere su grupo </h5>
            <% end %>
            <br><br>
        </div>
    </div>
</div>
